name = "Modified Hugo Fresh for Liman MYS"
license = "MIT"
licenselink = "https://github.com/StefMa/hugo-fresh/blob/master/LICENSE.md"
description = "A Hugo adaptation of the Fresh theme from CSS Ninja which is modified for Liman MYS by HAVELSAN Aciklab"
homepage = "https://github.com/StefMa/hugo-fresh"
tags = ["responsive", "one page", "light", "onepage", "company", "clean", "landing page"]
features = []
min_version = "0.45"

[author]
  name = "E. Berke Karagöz | Stefan M."
  homepage = "https://github.com/StefMa"
